# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "bundler", "~> 2.4.7"

gem "rspec", "~> 3.12.0"

gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.23.1"

gem "tty-box", "~> 0.7.0"